name: "Double D's Jounals"
permalink: :year/:month/:day/:title
baseurl: ''

# Your blog's start year and this year, showed in the footer left
# start is optional
start: 2017
now: 2021
 
# Social links showed in the footer
# You just need modify the nickname of github and twitter
link:
  email : daduki@gmail.com
  github : daduki
  twitter : caferoman

# Links in the navigation, you can modify both link name and link url
nav:
   Home: "/"
   Diary: "/"

   
markdown: kramdown
highlighter: rouge

sass:
  sass_dir: _sass
  style: compressed
